include: package:very_good_analysis/analysis_options.5.1.0.yaml
analyzer:
  errors:
    missing_return: error
    missing_required_param: error
    deprecated_member_use: warning
    deprecated_member_use_from_same_package: warning
  exclude:
    - "**/*.g.dart"
    - "lib/src/generated/**"
    - "lib/src/l10n/**"
linter:
  rules:
    public_member_api_docs: false
    constant_identifier_names: false
    prefer_relative_imports: true
    avoid_print: true
    prefer_single_quotes: true
