name: template_flutter_with_cubit_by_very_good
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^8.1.3
  dev: ^1.0.0
  dio: ^5.4.2+1
  dio_cache_interceptor: ^3.5.0
  flutter_bloc: ^8.1.4
  flutter_svg: ^2.0.10+1
  get_it: ^7.6.9
  injectable: ^2.4.1
  intl: ^0.18.1
  json_serializable: ^6.7.1
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.1.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
  build_runner: ^2.4.9
  injectable_generator: ^2.6.1
  retrofit_generator: ^8.1.0
  melos: ^5.3.0
  icon_font_generator: ^4.0.0

flutter:
  uses-material-design: true
  generate: true


  assets:
    - assets/images/
    - assets/vectors/

  fonts:
    - family: Jersey
      fonts:
        - asset: assets/fonts/Jersey_Regular.ttf
          weight: 400
        - asset: assets/fonts/Jersey_Regular.ttf
          weight: 500
        - asset: assets/fonts/Jersey_Regular.ttf
          weight: 600
        - asset: assets/fonts/Jersey_Regular.ttf
          weight: 700
    - family: UiIcons
      fonts:
        - asset: assets/fonts/UiIcons.ttf