// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB43iKsnUmBP8xuokv_A7LZebJHwHShXlk',
    appId: '1:622682520129:web:13efc4eba15b50fa4ce4c0',
    messagingSenderId: '622682520129',
    projectId: 'flutter-cubit-development',
    authDomain: 'flutter-cubit-development.firebaseapp.com',
    storageBucket: 'flutter-cubit-development.appspot.com',
    measurementId: 'G-TFVLGQN0FP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD6CVTF3R1GYii2Lc1maT11srlLQHJglw',
    appId: '1:622682520129:android:1d1d112cc00194d34ce4c0',
    messagingSenderId: '622682520129',
    projectId: 'flutter-cubit-development',
    storageBucket: 'flutter-cubit-development.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvP_lOZBz_MCul8gvVZNaBZU4ffdHjDJI',
    appId: '1:622682520129:ios:13ba40dce98e130e4ce4c0',
    messagingSenderId: '622682520129',
    projectId: 'flutter-cubit-development',
    storageBucket: 'flutter-cubit-development.appspot.com',
    iosClientId: '622682520129-jge8b8b4e6mrba059srpq6sut43ehmt0.apps.googleusercontent.com',
    iosBundleId: 'com.development.app',
  );
}
